# -*- coding: utf-8 -*-
"""myfirstapp

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BRosqoA0zowmVnpFYf_4y3sczlKx5itR
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile myfirstapp.py
# import streamlit as st
# import numpy as np
# import pandas as pd
# 
# st.header("My first Streamlit App")
# st.write(pd.DataFrame({
#     'Intplan': ['yes', 'yes', 'yes', 'no'],
#     'Churn Status': [0, 0, 0, 1]
# }))