# -*- coding: utf-8 -*-
"""mysecondapp

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17kU-uV-T1Lj1DbTRpm4SKhUE1297vf2P
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile myfirstapp.py
# import streamlit as st
# import pandas as pd
# 
# st.header("My second Streamlit App")
# 
# st.write('Before you continue, please read the [terms and conditions](https://www.gnu.org/licenses/gpl-3.0.en.html)')
# show = st.checkbox('I agree the terms and conditions')
# if show:
#     st.write(pd.DataFrame({
#     'Intplan': ['yes', 'yes', 'yes', 'no'],
#     'Churn Status': [0, 0, 0, 1]
# }))